---
deployment:
  tasks:
    - /bin/mkdir -p /home18/psicoterapiapyp/public_html/assets
    - /bin/cp -R assets/. /home18/psicoterapiapyp/public_html/assets/
    - /bin/cp index.html quienes-somos.html servicios.html contacto.html preguntas-frecuentes.html favicon.ico /home18/psicoterapiapyp/public_html/
